objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Stage__c</fullName>
        <inlineHelpText>The current status based on request.</inlineHelpText>
        <label>Lead Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>School Tour Requested</fullName>
                </value>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Meeting with Registrar</fullName>
                </value>
                <value>
                    <fullName>Application Received</fullName>
                </value>
                <value>
                    <fullName>Offered</fullName>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
                <value>
                    <fullName>Current Student</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Guardian</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_Level__c</fullName>
        <inlineHelpText>Enter the school level in which student seeks to have admission.</inlineHelpText>
        <label>School Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Junior School</fullName>
                </value>
                <value>
                    <fullName>Middle School</fullName>
                </value>
                <value>
                    <fullName>Senior College</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/PostalRating__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Range__c</fullName>
        <label>Range</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ranking__c</fullName>
        <label>Ranking</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Postal Rating</label>
</CustomObject>

classes/TestUpdateLeadPostCode.cls
@isTest
private class TestUpdateLeadPostCode {

 static testMethod void UpdateLeadPostCodeTest()    {
 
    PostalRating__c postalRating = new PostalRating__c();
    postalRating.Name = '1001';
    postalRating.Range__c = 'Within 10 Kms';
    postalRating.Ranking__c = 1;
    insert postalRating;
 
    Lead ld = new Lead();
    ld.FirstName = 'Jane';
    ld.LastName = 'Doe';
    ld.Lead_Type__c = 'Father';
    ld.Lead_Stage__c = 'Enquiry';
    ld.Status = 'Qualified';
    ld.School_Level__c = 'Junior School';
    ld.PostalCode = '1001';
    ld.Company = null;
    insert ld;
    }
    
    static testMethod void CampaignMemberesUpdateTest() {
        Campaign campaign = new Campaign(Name = 'Test Campaign', Type = 'Advertisement' );
        insert campaign ;
        
        Lead lead = new Lead();
        lead .FirstName = 'Jane';
        lead .LastName = 'Doe';
        lead .Lead_Type__c = 'Father';
        lead .Lead_Stage__c = 'Enquiry';
        lead .Status = 'Qualified';
        lead .School_Level__c = 'Junior School';
        lead .PostalCode = '1001';
        lead .Company = null;
        insert lead;
        
        CampaignMember campaignMember = new CampaignMember( CampaignId = campaign.Id, LeadId = lead.Id, Status = 'Sent' );
        insert campaignMember ;
        
        update lead;
    }
}